name: "TF_checker"

on:
  push:
   branches:
     -main
  #schedule:
  # - cron: "* * * * *"  # scheduled at 06:00 (UTC+8) everyday
  workflow_dispatch:

env:
  RUN_ENV: 'prod'

     
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
        
      - name: Run a one-line scripts
        run: |
          python -m webbrowser "https://www.youtube.com/?gl=UA&hl=uk"
          
  build_2:
   runs-on: windows-latest
  steps: 
     - name: Run a one-line scripts
        run: start https://stackoverflow.com
