name: "TF_checker"

on:
  #push:
   #branches:
     #-main
  schedule:
    - cron: "0,10,20,30,40,50 * * * *"  # scheduled at 06:00 (UTC+8) everyday
 # workflow_dispatch:
#
#env:
#  RUN_ENV: 'prod'

     
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        run: echo "dd#"
