name: "TF_checker"

on:
  push:
   branches:
     -main
  #schedule:
  # - cron: "* * * * *"  # scheduled at 06:00 (UTC+8) everyday
  workflow_dispatch:

env:
  RUN_ENV: 'prod'

     
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        
      - name: Run a one-line scripts
        run: |
          echo "https://www.youtube.com/?gl=UA&hl=uk"
          xdg-open https://www.youtube.com/?gl=UA&hl=uk
          gnome-open https://www.youtube.com/?gl=UA&hl=uk
          python -m webbrowser "https://www.youtube.com/?gl=UA&hl=uk"
